# Generated by Django 5.0.4 on 2026-04-25 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_buy_and_sell', '0004_banner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('opening_hours', models.CharField(default='10:00 AM - 7:00 PM', max_length=120)),
                ('is_authorized', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TradeInRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('bike_brand', models.CharField(max_length=100)),
                ('bike_model', models.CharField(max_length=100)),
                ('model_year', models.PositiveIntegerField()),
                ('expected_price', models.PositiveIntegerField()),
                ('condition', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Needs Work', 'Needs Work')], max_length=20)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='bikebuyandsell',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='bikebuyandsellimage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='bikebuyandsell',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bikebuyandsell',
            name='condition',
            field=models.CharField(choices=[('Used', 'Used'), ('Certified Used', 'Certified Used'), ('Like New', 'Like New')], default='Used', max_length=30),
        ),
        migrations.AddField(
            model_name='bikebuyandsell',
            name='engine_capacity',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bikebuyandsell',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bikebuyandsell',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bikebuyandsell',
            name='is_negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bikebuyandsell',
            name='location',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='bikebuyandsell',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, help_text='Mileage in kilometers', null=True),
        ),
        migrations.AddField(
            model_name='bikebuyandsell',
            name='model_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Bank Transfer', 'Bank Transfer'), ('Mobile Banking', 'Mobile Banking')], default='Cash on Delivery', max_length=50),
        ),
        migrations.AlterField(
            model_name='bikebuyandsell',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bike_buy_and_sell.orders'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.CharField(max_length=20, null=True, verbose_name='Total Price'),
        ),
        migrations.CreateModel(
            name='FinancingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('monthly_income', models.PositiveIntegerField()),
                ('down_payment', models.PositiveIntegerField()),
                ('employment_type', models.CharField(choices=[('Salaried', 'Salaried'), ('Business', 'Business'), ('Freelancer', 'Freelancer'), ('Student', 'Student')], max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_bike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bike_buy_and_sell.bikebuyandsell')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('preferred_date', models.DateField()),
                ('preferred_slot', models.CharField(choices=[('10:00 AM', '10:00 AM'), ('12:00 PM', '12:00 PM'), ('3:00 PM', '3:00 PM'), ('5:00 PM', '5:00 PM')], max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_bookings', to='bike_buy_and_sell.bikebuyandsell')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bike_buy_and_sell.bikebuyandsell')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('bike', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='bike_buy_and_sell.bikebuyandsell')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'bike')},
            },
        ),
    ]
