# Generated by Django 5.0.4 on 2026-04-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_buy_and_sell', '0005_contactmessage_servicecenter_tradeinrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financingapplication',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectionbooking',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradeinrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
